GalSim-developers/GalSim

- CHANGELOG.md
- galsim/__init__.py
- galsim/_pyfits.py
- galsim/catalog.py
- galsim/des/des_meds.py
- galsim/des/des_psfex.py
- galsim/des/des_shapelet.py
- galsim/fits.py
- galsim/fitswcs.py
- galsim/real.py
- galsim/scene.py
- galsim/wcs.py
- galsim/wfirst/wfirst_psfs.py
- tests/test_fitsheader.py
- tests/test_image.py
- tests/test_wfirst.py
This is a fairly small PR to address some failures in the test suite for older versions of pyfits.  I have a system with pyfits 2.4 that was failing many of the FitsHeader tests we introduced in #590.  So I fixed those.
The two changes that matter for people who don't care about that are:
1. I now allow a FitsHeader to be constructed from a list of (key, value) pairs in addition to a pyfits.header or a dict.  And I made that the way the repr works when there isn't a more succinct string to use, rather than the string version of the pyfits.Header object.  (The latter didn't work for my old pyfits, but also I think the list of (key, value) pairs looks cleaner in those cases anyway.)
2. I also took the opportunity to move our pyfits import out of `__init__.py` and into `_pyfits.py`.  So now …
> Pyfits 2.4 compatibility.

- CHANGELOG.md
- galsim/chromatic.py
- galsim/utilities.py
- tests/test_chromatic.py
- tests/test_utilities.py
This PR implements two caches in order to avoid recomputing intermediate products that can recur when drawing chromatic objects.  Specifically, these are the integral of the product of SED and bandpass for separable objects, and the effective profiles used in ChromaticConvolution.drawImage.  
The former cache only leads to a speedup of ~10% for the simple test I tried, but this probably depends somewhat on how finely the SED*bandpass integrand is sampled so could be more important in other cases.
The latter cache improves the timing of some ring test code in chroma by a factor of ~18.
The only tricky part I think worth mentioning is that since numpy ndarrays and lists are not hashable, in a few places I had to convert these into tuples to get the cache algorithm to work.
> #670 chromatic caches

- galsim/wfirst/wfirst_psfs.py
This is a short pull request that includes an option to have a higher-fidelity representation of the WFIRST PSFs in Fourier space compared to what you get with the default settings.  See the plots on the issue page for details of how this setting changes the MTF.
I did not put this into the CHANGELOG because this PR will go into the same release as the initial PR for the WFIRST module, so it's basically a slight improvement of one of the new features in this version of GalSim rather than an improvement on a previous version of GalSim.
There is a debatable philosophical point here related to how the WFIRST module is set up:
Unlike OpticalPSF or ChromaticOpticalPSF, the user cannot adjust all the parameters related to the WFIRST optical PSF freely.  Instead, the WFIRST module getPSF() …
> #661 - WFIRST module accuracy parameters

- galsim/interpolatedimage.py
- include/galsim/SBTransformImpl.h
- src/SBTransform.cpp
@danielsf reported an failure in `scons tests` when he ran it on his system:
```
.....................................................................................................................................F.....................................................................................................................................................................................................
======================================================================
FAIL: Test how getCOSMOSNoise works when applied to an image with a WCS.
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/danielsf/physics/lsst_150412/DarwinX86/anaconda/master-g68783b1848/lib/python2.7/site-packages/nose/case.py", line 197, in …
```
> #688 Fix pickling error for InterpolatedImage

- CHANGELOG.md
- galsim/base.py
- galsim/image.py
- tests/test_calc.py
(Take 2, this time to merge into master.)
Adding three new methods of GSObject to calculate the half-light radius, sigma=sqrt(T/2), and the fwhm for profiles that don't have these already as attributes.
We're thinking of using these on branch #693. They aren't necessarily hugely optimized for either speed or accuracy. Tests indicate that at least for Gaussian and Exponential, the defaults are accurate to 1 decimal place, which is probably sufficient for the kinds of uses we are planning for them. There are parameters to allow for greater accuracy if desired.
> #308 Code to calculate HLR, Sigma, FWHM

- CHANGELOG.md
- galsim/base.py
- galsim/chromatic.py
- galsim/image.py
- galsim/optics.py
- galsim/real.py
- galsim/scene.py
- tests/test_base.py
This PR addresses issues #682 and #657, both related to documentation.
For #682, I added documentation about what our convention for x,y is in terms of the rows and columns in the numpy array. I also added some concrete examples that will hopefully make clear what some of the image methods that shift around the coordinates do.  @esheldon Please see if the documentation update here addresses your concerns.
For #657, I tried to improve the documentation about the units used in Airy, OpticalPSF and Kolmogorov.  In particular with respect to the units of the `lam_over_diam` and `lam_over_r0` parameters.  I also added a calculation of lam / r0, giving those values directly for Kolmogorov, analogous to the lam / diam calculation that Rachel added to Airy and OpticalPSF.  @dkirkby Please see if …
> #682 Improved documentation about coordinates and units.

- INSTALL.md
- SConstruct
- tests/SConscript
At the DESC hack day today, we tried to install GalSim with Anaconda Python on @cwwalter's laptop.  But we ran into a new problem introduced by El Capitan, the latest MacOS.  They decided to institute a new policy called "System Integrity Protection" (SIP).  Probably, this is really important for stopping terrorists from taking over the world.  But for running SCons properly, it was a big headache.
Basically, SIP involved removing dangerous environment variables like LD_LIBRARY_PATH and DYLD_LIBRARY_PATH from system calls.  So within SCons, or when SCons calls system commands to see if things can run properly, it fails if you system is relying on these variables to find the right libraries at runtime.
The solution is twofold:
1. Add scons options to let the user explicitly give …
> #721 Fix SCons for El Capitan when DYLD_LIBRARY_PATH is needed

- CHANGELOG.md
- INSTALL.md
- galsim/bandpass.py
- galsim/base.py
- galsim/chromatic.py
- galsim/fitswcs.py
- galsim/image.py
- galsim/sed.py
- galsim/table.py
- galsim/transform.py
- galsim/wcs.py
- include/galsim/Table.h
- pysrc/Table.cpp
- src/Table.cpp
This is a quick PR in response to @jchiang87's [Photometry Bakeoff](https://github.com/jchiang87/PhotometryBakeoff) results.  This was using the GalSim Bandpass and SED classes in a way that we never really tried to optimize for speed.  So it turned out the code wasn't terribly fast.  
Here (on branch table_speedup) I made a few simple changes to speed things up.
1. Use pandas to read in the text file if it's available, falling back to the old (and much slower) `numpy.loadtxt` function.  This wasn't actually part of Jim's timings, since he started the clock after the SED and Bandpass were both loaded.  But it makes a huge difference in the overall running time of the galsim_baker script.
2. Add a function to the C++ Table class that can interpolate many values at once.  This saves a huge …
> Table speedup

- SConstruct
This makes it easier to build GalSim against buggy Python builds (such as the one shipping with Anaconda; see https://github.com/ContinuumIO/anaconda-issues/issues/498).
Note: in most cases one can get away with adding the path to libpython*.dyld onto `DYLD_LIBRARY_PATH`, but having it on `DYLD_FALLBACK_LIBRARY_PATH` ensures nothing else gets picked up from it that would otherwise get picked up from system paths. E.g., Anaconda also ships with `libz`, but one probably wants to build against the system version, not the Anaconda one.
Related issues: https://jira.lsstcorp.org/browse/SIM-1895, https://github.com/lsst/galsim/pull/9
> Pass DYLD_FALLBACK_LIBRARY_PATH to scons

- examples/demo9.py
- examples/demo9.yaml
- examples/great3/cgc.yaml
- examples/json/demo9.json
- galsim/config/extra_truth.py
- galsim/config/value.py
- galsim/scene.py
- tests/test_scene.py
As described in #738, there was a bug in tracking the original COSMOS catalog index for parametric galaxies that use the Sersic galaxy model.  If a transformation (like lensing) was later applied to those objects then the original catalog index was not retained.  On this branch:
- That bug was fixed.  I also made a unit test that would catch the issue on the python side (not the config side), but did not add the bug fix to the CHANGELOG since the truth table functionality is new in v1.4.
- Some of the demos were updated to include more information in the output truth tables (e.g., location of the galaxy within a larger image, and index in the COSMOS catalog).
- Mike made some of the error messages when using the wrong syntax for output truth tables more informative.
> #738 - small bug in writing output truth tables

- INSTALL.md
URL was still pointing to Google Code, but version >= 0.72 cannot be downloaded from there.
> Update tmv repo URL

- .travis.yml
This PR adds a .travis.yml file, which enables integration with the Travis-CI continuous integration service. It replaces the Jarvis CI system, which has not been working for a while since I've been unable to get galsim properly installed there, among other problems.
An example run on this fork can be seen at:
https://travis-ci.org/joezuntz/GalSim/builds/132622083
there are currently no errors but there are some warnings that it might be worth looking into!
If this PR is okay then there are a few more steps to enabling Travis for main GalSim repository:
- Sign up at travis-ci.org with the GalSim-developers account and accept the github permissions
- Go to https://travis-ci.org/profile/Galsim-developers and enable CI for galsim
All the best,
Joe
> Add a Travis-CI YAML file for continuous integration

- CHANGELOG.md
- galsim/compound.py
- tests/test_compound.py
@ismael2395 pointed out (cf. #763) a subtle bug where the str and repr of objects that are a Transform(Sum(Transform(obj))) were messed up.  
I tracked it back to an "optimization" we do in the Sum (and Convolution) constructors to skip much of the function if the list has only a single element.  But it turns out in this case to lead to the bug he found.
Seems like the easiest solution is to just not do that.  I'm sure this is never anything close to an actual optimization, so just let them both go through the motions of the full constructor even though some of the operations are trivial when there is only a single element.
> #763 Fix a bug in the Sum and Convolution constructors when the list has only one object.

- CHANGELOG.md
- galsim/image.py
- tests/test_image.py
This is a tiny little bug fix that I ran across working on Piff.  If I used `im2 = galsim.Image(im, dtype=dtype)`, then the wcs attribute of `im` was not properly transfered over to `im2`.  I added some unit tests that check this and added 2 lines to `image.py` to fix the bug.
> Fix bug in Image constructor where wcs wasn't copied if image is an Image

- examples/demo13.py
This is a 1-line PR aimed to fix a minor bug in creating a background image that is subtracted from the galaxy images. The previous background image was quantized only once where as the galaxy images are quantized as multiple stages - integer photon counts, integer electron counts and quantization in ADU. Quantizing the background image only once could slightly underestimate the true background, which could have significant impact for galaxies with low flux.
> Quantizing the background image correctly in demo13

- galsim/phase_screens.py
- galsim/utilities.py
- tests/test_phase_psf.py
I finally got around to comparing the simulated phase screen structure function out of AtmosphericScreen to an analytic prediction (as recommended by George Angeli and Bo Xin some weeks ago).  This turned up a small but important bug in the AtmosphericScreen constructor, where the screen size was tweaked to yield a good FFT size, but this wasn't properly reflected in the `.screen_size` attribute.  So I fixed that and added a couple of unit tests.
Also, here's the theory vs. simulated structure functions (D(r) = <|phi(x) - phi(x+r)|^2>) now:
Pretty decent agreement I think at scales far from the screen sampling interval (0.05 m) and screen size (100.0 m).
> Fix atmospheric screen size

- examples/des/des_wcs.py
The des_wcs.py module was trying to load from DES ccd images that don't exist.  Skip these "bad ccds"
> skip bad CCD images when loading DES wcs

- src/hsm/PSFCorr.cpp
This is an exceptional condition that can occur sometimes
(because it certainly does occur!), rather than something
that should bring the world to a screaming halt.
> HSM: replace assertion with exception

- SConstruct
@esheldon reported in #790 that boost on Ubuntu uses a non-standard name for its Python 3 boost-python library.  This update just adds that name to the search list for when SCons is trying to figure out what the right linking command will be.
Probably there's not much to review here other than for Erin to confirm that it works on his Ubuntu system (which he already did, but then I changed things slightly, so... again please?) and for other people to make sure it doesn't break anything on their systems.
> #790 Update name of boost python 3 library in SCons for Ubuntu

- src/SBDeconvolve.cpp
- tests/test_compound.py
- tests/test_metacal.py
This fixes a bug identified by @esheldon in issue #834 that I accidentally introduced in #799.
I added two new unit tests.  The one in test_metacal.py is pretty close to what Erin posted in the bug report.  The other (in test_compound.py) is a bit closer to the proximate source of the error and tests that a transform commutes with a deconvolve.  (Other than the flux scaling, which isn't expected to commute.)
> Fix bug in Deconvolve drawK with non-rectilinear steps

- CHANGELOG.md
- galsim/compound.py
- galsim/fits.py
- galsim/image.py
- galsim/interpolatedimage.py
- galsim/phase_psf.py
- galsim/phase_screens.py
- galsim/sed.py
- galsim/table.py
- include/galsim/SBInterpolatedImage.h
- include/galsim/SBInterpolatedImageImpl.h
- pysrc/SBInterpolatedImage.cpp
- src/SBInterpolatedImage.cpp
- tests/galsim_test_helpers.py
- tests/test_base.py
- tests/test_interpolatedimage.py
- tests/test_optics.py
- tests/test_phase_psf.py
This PR adds `_force_stepk` and `_force_maxk` kwargs to `OpticalPSF` by simply forwarding them to `PhaseScreenPSF`, where they were already available.  Additionally, both `PhaseScreenPSF` and `OpticalPSF` get a new kwarg, `ii_pad_factor`, which gets forwarded to the wrapped `InterpolatedImage` as `pad_factor`.  
(Note, we already have a (poorly named) `pad_factor` keyword for `OpticalScreen` and `PhaseScreenPSF`, which adjusts the size of the image to be passed to the `InterpolatedImage` (though it doesn't actually do any padding, it just uses a larger image to reduce FFT aliasing).  We could think about renaming the `PhaseScreenPSF` and `OpticalPSF` `pad_factor` kwarg to something like `bounds_factor`, and then the new `ii_pad_factor` could just be `pad_factor`, but I think it may be …
> #835 force_stepk, force_maxk, and ii_pad_factor

- CHANGELOG.md
- galsim/__init__.py
- galsim/bounds.py
- galsim/fft.py
- galsim/gsobject.py
- galsim/image.py
- galsim/interpolatedimage.py
- galsim/lensing_ps.py
- galsim/phase_psf.py
- galsim/phase_screens.py
- galsim/table.py
- galsim/transform.py
- galsim/utilities.py
- galsim/wcs.py
- include/galsim/Image.h
- pysrc/Image.cpp
- src/Image.cpp
- tests/test_draw.py
- tests/test_optics.py
This is basically all speed-related optimizations.  
Josh was comparing the timing of @aaronroodman's donutlib code to the equivalent functionality in GalSim's phase_psf and found that GalSim was significantly slower.  He made some changes in #835 to try to get the code to at least do the same thing in terms of padding and such.  But even with an apples-to-apples comparison, GalSim was still more than a factor of 2 slower.
Anyway, he and I have been working on some optimizations.  I think we're probably done so here they are.  Some highlights:
- Caching some of the calculations related to Zernikes that are independent of the wavefront and just a function of jmax.
- Faster horner implementation that beats np.polyval for the typical inputs we have in the phase_screen code by more than a …
> Optimizations for OpticalPSF code

- include/galsim/Image.h
- include/galsim/ImageArith.h
- include/galsim/Noise.h
- src/Image.cpp
- src/SBInterpolatedImage.cpp
- src/hsm/PSFCorr.cpp
- tests/test_hsm.py
- tests/test_interpolatedimage.py
- tests/test_random.py
In #799, I updated the Image class to work with arbitrary steps between the values in both directions, i.e. not require the underlying array to be C-contiguous.  However, I missed some uses that depended on the C-contiguousness of the array.  Since that's usually what we have, it didn't trigger any errors in the tests.
Anyway, Josh ran across one, which he reported in #833.  I fixed that and added unit tests that would have caught the problem.  There were also problems with the addNoise implementations, so I fixed that and added tests there as well.
SBInterpolatedImage serialize also used the error-prone iterators, although it always uses a C-contiguous image, so it wasn't ever a problem.  But I switched it anyway and removed the Image iterator methods.
> #833 Fix uses of Image when underlying array is not C-contiguous

- galsim/config/extra_psf.py
- galsim/config/stamp.py
- galsim/gsobject.py
- galsim/image.py
- galsim/noise.py
- galsim/phase_psf.py
- tests/galsim_test_helpers.py
- tests/test_base.py
- tests/test_config_image.py
- tests/test_config_noise.py
@brgillis reported in #845 that some tests were failing.  Turns out they were all due to numpy 1.7, which predates some accuracy improvements numpy made (I think in 1.9), especially in functions like `np.sum` which now accumulate in double precision, even if the array is single precision.  In numpy 1.7, the accumulator used whatever type the array was by default, although you can specify a different type using `dtype=float`.
This PR mostly amounts to adding that kwarg to many of our `np.sum(...)` calls.  It doesn't hurt anything on new numpy versions, and it makes things more accurate on old ones.
There were still a few places where the tests disagreed at the 5th decimal place, so there may be a couple more places where the numpy accuracy changed that I didn't find.  But for those, I just …
> #845 Backwards compatibility with numpy 1.7

- CHANGELOG.md
- galsim/image.py
- pysrc/Interpolant.cpp
- tests/test_image.py
@esheldon [reported](https://github.com/rmjarvis/Piff/issues/50) a bug running Piff unit tests that I eventually tracked down to a bug in GalSim that apparently only shows up for particular systems (Ubuntu Anaconda in his case).
The bug shows up if a suitably large image is loaded from a fits file, and subimages are taken from that image and stored.  Then if the main image goes out of scope and the file is closed, then accessing those stored subimages can cause seg faults.
I'm pretty sure the underlying issue is how we do our wrapping of the numpy arrays and how we set the owner of them, but I didn't fix it there, since I'm planning to rewrite all of that stuff relatively soon anyway as part of the no-boost migration.
Rather, I changed the `Image.subImage` call to make the subarray in …
> #842 Fix a bug in Image.subImage that can cause seg faults on some machines

- galsim/bandpass.py
- galsim/base.py
- galsim/des/des_psfex.py
- galsim/des/des_shapelet.py
- galsim/fits.py
- galsim/gsobject.py
- galsim/interpolatedimage.py
- galsim/phase_psf.py
- galsim/sed.py
- galsim/wfirst/wfirst_psfs.py
- tests/test_bandpass.py
- tests/test_des.py
- tests/test_sed.py
I went through and replaced a subset of the `isinstance(variable, str)` predicates with `isinstance(variable, basestring)`.  (It didn't seem necessary to replace all of them, like the ones where we check if `scale_unit` is a string, for example.)  
I also improved the eval string sanity check in `SED` and `Bandpass` to check that the inferred lambdas yield a float.
Finally, I made a number of small cleanups suggested by pylint on the files I looked through for cases of `isinstance(var, str)`.
> #851 str -> basestring

- galsim/catalog.py
- galsim/des/des_meds.py
- galsim/interpolatedimage.py
- galsim/table.py
- galsim/utilities.py
- tests/galsim_test_helpers.py
- tests/test_catalog.py
Numpy version 1.12 changed how `np.roll` works slightly, which broke one of our tests.  To make sure `galsim.utilities.roll2d` always returns a C-contiguous array, we now have to coerce it.
And astropy version 1.3 changes the name of the `clobber` kwarg for `writeto` to `overwrite`.  I have no idea what compelled them to make this change, but I can't be bothered to support both APIs, so I just implement the file removal ourselves in the two places that had used `clobber`.
> #861 Updates for latest numpy and astropy versions

- .travis.yml
- CHANGELOG.md
- README.md
- galsim/_version.py
- src/SBProfile.cpp
- tests/test_draw.py
@jchiang87 reported an occasional assert failure in issue #866.  It turns out that when the flux to be shot was 100001, it would shoot the first batch of 100000 and be left with 1 photon, which could with numerical rounding sometimes be 1 - epsilon.  This led to it going down a branch that I had thought was not possible, so it hit an assertion failure.
To address this, I both fixed the logic of that branch to use `N < 0.5` rather than `N < 1`, which is probably more appropriate.  And I also just don't do anything if `add_to_image == true` rather than assert that it should be `false` in case there is some other case that could hit this branch, so we don't have the possibility of an assert failure here.
Once merged into releases/1.4, this will be released as v1.4.3, so I included the …
> Fix photon shooting bug reported in #866

- CHANGELOG.md
- README.md
- galsim/_version.py
- include/galsim/Noise.h
- include/galsim/Random.h
- src/Random.cpp
- src/SBProfile.cpp
- tests/test_random.py
@jchiang87 found another bug when doing the LSST imsim run.  It turns out that the boost poisson deviate class that we use maxes out at 2^31 and wraps around to -2^31.
This turned out to be a problem when photon shooting with `poisson_flux=True` and the flux is >~ 2^31 (~2.1e9).  Then the poisson varied flux comes out negative, and it tries to shoot a negative number of photons, which isn't allowed.
This PR fixes this in two ways.  First, when the flux > 2^30, it uses a Gaussian approximation to the Poisson deviate to do the `poisson_flux=True` option.  And second, once it has its final number of photons to shoot, it checks again if N < 0, and if it is, it raises an error (rather than crashing with an assert failure down the line).
This PR is to merge into releases/1.4, which should be …
> #881 Use normal_distribution in PoissonDeviate when mean is very high

- CHANGELOG.md
- galsim/fitswcs.py
- include/galsim/WCS.h
- pysrc/WCS.cpp
- pysrc/files.txt
- pysrc/module.cpp
- src/WCS.cpp
- src/files.txt
When working on WFIrst stuff, Troxel found a bug in the GSFitsWCS class where it would sometimes not converge going from ra,dec -> x,y when the WCS included a SIP component.  Basically, the target precision (1.e-8 arcsec) was too tight to always be able to meet it in double precision.  
So I adjusted the tolerance to 1.e-6 arcsec (which should still be plenty), and now it checks if the relative changes in x,y are below 1.e-15, in which case it declares it to be converged regardless of the agreement with the sky value.
I also moved this bit to C++, since it was rather slow to do the iteration in python with numpy.linalg.  Now it uses TMV, which is quite a bit quicker.
> #880 Fix error in ra,dec -> x,y for SIP convergence

- galsim/chromatic.py
- galsim/real.py
- galsim/sed.py
- src/RealGalaxy.cpp
- tests/test_config_output.py
- tests/test_sed.py
1. Don't use `np.moveaxis` if it doesn't exist.  I think the workaround (using two `swapaxes` calls) may be equally efficient, but I'm not sure, so I left in the `moveaxis` version to use when possible and only do the workaround if necessary.
2. I was getting a failure in the test of the `retry_io` feature.  It worked fine when running `python test_config_output.py` or `nosetests`, but not `scons tests` which runs nosetests in multiprocessing mode.  I still don't completely understand why it was not working properly, but I switched the test to setup the rng more like how we normally do things in config, using `galsim.config.GetRNG` rather than using a local variable.  That made it work, so I don't think there is any bug in the backend code.  Just the test seems to have been a bit fragile.
> #898 Two fixes to make GalSim run at Nersc

- SConstruct
- src/SConscript
This is the second batch of fixes required to build GalSim with a Python3 SCons.
I have successfully built GalSim using `scons-3.0.0.alpha.20170614.tar.gz` with Python3 but there is one issue I encountered with building of boost-python because those include files have bad Unicode in them for an author string. I've reported this upstream (and I have a local fix).
> More python3 fixes

- galsim/gsobject.py
- tests/test_draw.py
I think drawing a zero-flux object with photon shooting should just return a 0 photon image.  This comes up occasionally when photon-shooting chromatic objects, where `sed(w)*bandpass(w)` can sometimes be zero at one of the sampled wavelengths.  (Photon-shooting chromatic objects doesn't quite work yet, but I've started thinking about it...)
This PR is just to avoid the divide-by-zero error currently encountered on master when photon-shooting a zero-flux object.
> Permit zero-flux drawPhot

- include/galsim/Noise.h
- include/galsim/Random.h
- include/galsim/hsm/PSFCorr.h
- pysrc/HSM.cpp
- pysrc/Interpolant.cpp
- pysrc/Random.cpp
- pysrc/Table.cpp
- src/hsm/PSFCorr.cpp
This addresses an incompatibility found when python/boost/numpy etc. are compiled with gcc `7.2.0` and galsim is compiled with `6.2.0`.  This is an issue for interfaces between the C++ and python generated by boost-python
With these changes the tests all pass.
I only modified the interfaces for which a test failed, I did not exhaustively change all interefaces.  There could be some not covered by tests which would still exhibit this error.
> Use char * rather than std::string in C++ interfaces

- galsim/wfirst/wfirst_bandpass.py
- tests/test_wfirst.py
This PR has some documentation updates and a minor code update that cleans up `wfirst_bandpass.py` (during the change from v1.4->1.5, some lines of code should have been removed, but were not, so there was a kwarg that did nothing).  Since there is no actual new functionality or bug fix in the usual sense, I did not update CHANGELOG.
As discussed in the last comment on issue #923, I will open an issue for the more general zeropoint issue (definition and need for demos) once this PR is merged.
> #923 - documentation and minor code updates

- CHANGELOG.md
- galsim/phase_psf.py
- galsim/utilities.py
- tests/test_phase_psf.py
This PR fixes the memory leak described in #942.
I decided my original plan to just delete PSFs from `_pending` after drawing them using either `method='phot'` or `method='fft'` doesn't actually work, since it ought be possible to do both in sequence without losing the speed advantage offered via `_pending`.
My new idea is to instead use the`weakref` module.  This lets a `PhaseScreenList` still refer to any dependent `PhaseScreenPSF`s in the `_pending` list, but won't keep them alive if those weak references are the only references to the PSFs, thus eliminating the memory leak.
> Fix memory leak in PhaseScreenPSF

- CHANGELOG.md
- galsim/__init__.py
- galsim/vonkarman.py
- include/galsim/LRUCache.h
- include/galsim/SBVonKarman.h
- include/galsim/SBVonKarmanImpl.h
- pysrc/SBVonKarman.cpp
- pysrc/files.txt
- pysrc/module.cpp
- src/SBVonKarman.cpp
- src/files.txt
- tests/galsim_test_helpers.py
- tests/test_vonkarman.py
This PR adds the VonKarman profile, which is a generalization of a Kolmogorov profile that adds an outer scale to the modeled atmospheric turbulence power spectrum.
This code emerged as part of the effort to implement a "second kick" profile that would help with photon shooting an atmospheric phase screen PSF.  Rather than trying to cherry-pick specific commits from that development branch, I found it easier to just copy the appropriate subset of files into a new branch and make a single commit.  So I'm afraid reviewers won't get to see my normal set of false-starts and other fumblings on this PR, (though they're still available in the `secondkick` branch).
The main surprise I encountered with the VonKarman profile was the realization that at its center, there's formally a delta-function …
> VonKarman profile

- CHANGELOG.md
- src/OneDimensionalDeviate.cpp
- src/SBKolmogorov.cpp
- tests/test_base.py
@jchiang87 reported in #952 a combination of input parameters that sent Kolmogorov into an endless loop.  Turns out the problem was in OneDimensionalDeviate.  Specifically the `findExtremum` call ended up having x1 increase without bound until it was inf (and then kept looping unchanged).
The underlying problem seems to be the fatRight case not being properly set up.  It set new values for x1,x2,x3 that didn't preserve the intended invariance that x1 < x2 < x3.  In fact, I'm not even sure how this code used to function properly (which apparently it usually did).
Anyway, I restructured the algorithm a bit and added (when DEBUGLOGGING is enabled) some assert statements to make sure the loop invariants are preserved properly.  It does seem to be working properly now.
TODO on merge:
> #952 Fix error in findExtremum not preserving intended invariants

- CHANGELOG.md
- galsim/angle.py
- galsim/config/input_fitsheader.py
- galsim/lensing_ps.py
- galsim/nfw_halo.py
- galsim/pse.py
- src/SBVonKarman.cpp
- tests/galsim_test_helpers.py
- tests/test_deprecated.py
- tests/test_lensing.py
- tests/test_pse.py
This PR is mostly just additional tests to improve the test coverage of lensing_ps.py, nfw_halo.py and pse.py.  In a couple cases I marked stuff as `pragma: no cover` rather than write the tests for functions that are never really used within GalSim.  And in a couple other cases where we never use options, I went ahead and deprecated them.
Deprecated:
* passing `Image` arguments to `kappaKaiserSquires` function
* `interpolant` argument for PowerSpectrum methods `getShear`, `getConvergence`, `getMagnification`, and `getLensing`.  
Explicitly uncovered:
* `calculateXi` (There is some coverage, but not nearly for all the possible parameter options, and I didn't want to bother with it.  This was relevant during Great3, but I'm not sure how useful it is anymore.  I wouldn't mind deprecating …
> #855 Improve test coverage of lensing module

- src/SBVonKarman.cpp
- tests/test_vonkarman.py
Fix the bug @areshernandez found for certain r0 values in initializing a VonKarman profile, reported in #957.
The resolution was to add explicit split points for the GKP integration at the zeros of the Bessel function.  This is a trick we've employed for both Moffat and Sersic with similar integrals that involve Bessel functions.  In general, forcing splits at the first few zeros of an oscillating function makes the integral much more stable in my experience.
> Add explicit split points for the VK rawXValue integral

- CHANGELOG.md
- galsim/phase_psf.py
- galsim/phase_screens.py
- galsim/zernike.py
- tests/test_deprecated.py
- tests/test_zernike.py
This PR 
1) Adds analytic Zernike gradients (replacing the finite difference gradients I had been using for optical screen geometric photon-shooting)
2) Changes the Zernike implementation to use coefficients in x and y coordinates instead of coefficients in (x + iy) and (x^2 + y^2) coordinates.
The first change increases speed by only requiring two calls to `horner2d` instead of three, and also eliminating subsequent array operations to create finite differences.
The second change increases speed since all of the work performed becomes part of the final result, compared to before where we would perform work using complex numbers and at the last step only keep the real parts.
Overall, I find a speed increase for evaluating Zernikes of about a factor of 2, and for evaluating Zernike …
> Analytic Zernike Gradients #832

- galsim/phase_psf.py
- galsim/table.py
- tests/test_phase_psf.py
@jchiang87 found [here](https://github.com/LSSTDESC/imSim/pull/101#issuecomment-386907091) a bug that boiled down to a failure in the phase gradient shooting code to shoot just a single photon.  This PR adds a test and fix for this, plus a test and fix for shooting 0 photons.
> Phase gradient photon shooting with 0 or 1 photons

- galsim/__init__.py
- galsim/phase_psf.py
- galsim/phase_screens.py
- tests/test_deprecated.py
- tests/test_phase_psf.py
I think I'm happy with this now.  I avoided using copy/pickle in `withGSParams()`, and also updated the pickling so that it doesn't assume that `prepareDraw` has been called.  There a bunch more tests in place to check that A) `_wavefront()` isn't needed in order to pickle/copy/change GSParams or draw using photon-shooting and B) make sure that copying, changing GSParams, and drawing are appropriately commutative.
> #990 fix PhaseScreenPSF.withGSParams

- .travis.yml
- galsim/fits.py
- galsim/fitswcs.py
- galsim/noise.py
- galsim/random.py
- src/Random.cpp
- tests/test_config_image.py
- tests/test_fitsheader.py
- tests/test_random.py
- tests/test_wcs.py
@jchiang87 and @villarrealas were getting seg faults when trying to generate random Poisson deviates with mean=0.  
This PR fixes this, so that PoissonDeviate(mean=0) always generates 0's.  This seems to be the mathematically consistent thing to do, although I'll note that [Wikipedia](https://en.wikipedia.org/wiki/Poisson_distribution) says that the Poisson deviate is only defined for mean > 0.
I also make sure that it raises an appropriate exception when mean < 0.  Also, while debugging this I noticed that our repr for PoissonDeviate actually looked like a BaseDeviate.  We never really check the repr of deviates, since we don't expect them to round trip.  But they should at least round trip to the correct type if not an equivalent object.  So I fixed that too.
I'd request a fast …
> Make sure PoissonDeviate works with mean=0

- galsim/fits.py
- galsim/fitswcs.py
- tests/test_fitsheader.py
- tests/test_wcs.py
@beckermr ran into an issue where he had a fits "header" (really just a dict) that had lowercase keys.
The [FITS standard dictates uppercase letters only in header keys](https://fits.gsfc.nasa.gov/standard40/fits_standard40aa-le.pdf) (4.1.2.1), so this is technically user error.  But we should be accommodating, so this PR basically just makes sure to convert all keys to uppercase on creation of a FitsHeader object so the input dict can use either format.
>  Make sure FitsWCS works if input header has lowercase keys

- galsim/phase_psf.py
- galsim/phase_screens.py
- galsim/table.py
- galsim/utilities.py
- galsim/zernike.py
- tests/test_phase_psf.py
- tests/test_table.py
- tests/test_utilities.py
- tests/test_zernike.py
The PR addresses #1006.  I have:
• Explicitly implemented shared memory for atmospheric screens using `multiprocessing.RawArray` and `.RawValue` classes.  The main impact going forward is that we would no longer need to rely on esoteric *nix fork() + copy-on-write behavior to effect shared memory in applications like ImSim.  A secondary impact is that when using the "spawn" launch context, subprocesses should now be able to safely use OpenMP (I hope, this is untested).
• Added an `mp_context` kwarg to `AtmosphericScreen` so that the user can control what multiprocessing launch context to use.  The default of `None` falls back to the python stdlib default, which is "fork".
• Added a couple of helper functions to ease use of shared memory via `multiprocessing.Pool` objects.  See …
> Use shared memory for AtmosphericScreen

- CHANGELOG.md
- galsim/catalog.py
- galsim/fits.py
- galsim/fitswcs.py
- galsim/integ.py
- galsim/lensing_ps.py
- galsim/main.py
- galsim/nfw_halo.py
- galsim/phase_psf.py
- galsim/random.py
- galsim/table.py
- galsim/utilities.py
- galsim/wcs.py
- galsim/zernike.py
- tests/test_random.py
- tests/test_wcs.py
This PR includes a few bug fixes I think we should include in the 2.1 series as v2.1.5:
1. @aamon pointed out a bug in the WCS functions where things like `local` would fail when given a PositionI input rather than a PositionD.  This is a casualty of a few-years-old change in numpy behavior to disallow subtracting a float from an int with `-=` (and similar ops).  But apparently it's rare enough that no one noticed it being a problem until now.  Anyway, the fix is just to build most of our numpy arrays with `dtype=float`.  I went through and checked them all and fixed the ones that looked potentially problematic, but I only added a unit test for the error that Alex was getting.
2. PyYAML changed its `load` function to raise ugly errors telling people to switch to `safe_load` instead or …
> #1024 A few bug fixes I'd like to add to v2.1 series (v2.1.5)

- CHANGELOG.md
- galsim/fitswcs.py
- galsim/wcs.py
- requirements.txt
- tests/test_wcs.py
@esheldon and @beckermr were finding their use of the `toWorld` method of the WCS classes to be slow, since they were applying to many positions at one, and the only public API requires doing these calculations one at a time using PositionD instances for the positions.
The backend code for our WCS classes allows numpy arrays for the `toWorld` function using either `_uv` or `_radec` (depending on which kind of WCS it is), but there was no public method that gave documented access to these methods.
So this PR adds vectorized front end versions of `toWorld` that work with numpy arrays.  I also added vectorized versions of the reverse operation `toImage`, which required a bit of development on the backend as well, since those hadn't always worked correctly with numpy arrays.
The new front end …
> #1026 Add vectorized versions of toWorld and toImage

- CHANGELOG.md
- include/galsim/Solve.h
- src/SBSersic.cpp
- tests/test_sersic.py
When n is very very close to 0.5, the Sersic class's calculation to determine a good stepk could fail to converge.  My solution here is the just make sure the initial bracketing is at least 0.01.  With this starting point, the bracketing takes only a few iterations, and the Brent solution takes 1 step.  So I think this is a good, efficient solution for this edge case.
> #1041 Fix brackeyUpper failure for Sersic galaxies with n very very close to 0.5.

- galsim/download_cosmos.py
This PR simply updates the download link for the COSMOS dataset to use the Zenodo hosted copy of the data. This aims to address  #1033 and #1037 in part.
Note that I'm not digging deaper into the  download mechanism here, we may ultimately want to use something a little bit more robust that can handle download interruptions (this is the reason why the current download from Great3 server was failing, because the server could only download 1GB at a time),
> Updates download URL for  COSMOS dataset to Zenodo

- CHANGELOG.md
- galsim/correlatednoise.py
- galsim/interpolant.py
- galsim/interpolatedimage.py
- galsim/real.py
- include/galsim/Interpolant.h
- pysrc/Interpolant.cpp
- src/Interpolant.cpp
- tests/test_correlatednoise.py
- tests/test_deprecated.py
- tests/test_interpolatedimage.py
The main thing here is to expose some of the Interpolant functions that had been confined to the C++ layer.  In particular the ability to calculate xval and kval for an array of input values.  This is Issue #1038.  We want this functionality (the xval part) for use in Piff.
Along the way, I significantly beefed up the unit testing of the Interpolant classes.  No significant bugs found, which was good.  However, I did notice that our use of the `tol` parameter isn't really consistent with the rest of GalSim.  It was basically being used the way we normally use `kvalue_accuracy`.  And the default of `1.e-4` doesn't match the default `kvalue_accuracy=1.e-5`.  Furthermore, quite a few of the classes don't even use `tol` for anything now that they have working analytic functions for …
> #1038 Updates to Interpolant classes

- CHANGELOG.md
- include/galsim/Interpolant.h
- include/galsim/OneDimensionalDeviate.h
- src/Interpolant.cpp
- src/OneDimensionalDeviate.cpp
- src/SBAiry.cpp
- src/SBExponential.cpp
- src/SBKolmogorov.cpp
- src/SBSecondKick.cpp
- src/SBSersic.cpp
- src/SBSpergel.cpp
- src/SBVonKarman.cpp
- tests/test_airy.py
- tests/test_box.py
- tests/test_exponential.py
- tests/test_gaussian.py
- tests/test_interpolatedimage.py
- tests/test_kolmogorov.py
- tests/test_moffat.py
- tests/test_optics.py
- tests/test_phase_psf.py
- tests/test_second_kick.py
- tests/test_sersic.py
- tests/test_spergel.py
- tests/test_vonkarman.py
@cwwalter ran across a bug in photon shooting where we were systematically shooting a little bit less total flux than intended for some profiles.  The problem occurred with profiles that use OneDimensionalDeviate for their back-end shooting calculations.  Indeed there were actually two problems:
1. Two profiles, Kolmogorov and VonKarman, used the wrong tolerance value for when to stop the radial profile.  We advertise that errors in the shooting flux should be less than gsparams.shoot_accuracy, which defaults to 1.e-5.  These were erroneously using gsparams.folding_threshold/5 for no obvious reason.  The latter value is only 1.e-3, so this led to the shooting flux values being wrong by 1.e-3 in relative value rather than 1.e-5, which would probably have been tolerable.
2. All profiles …
> Fix the flux when shooting some profiles to not be off by ~1.e-3

- CHANGELOG.rst
- examples/demo9.py
- galsim/gsobject.py
- galsim/interpolatedimage.py
- tests/test_draw.py
- tests/test_wcs.py
Sorry, I lied.  One more PR for version 2.2.  This one is quick though.  It's a feature I've wanted to add for a while now, but I never bothered to make an issue for.
I added `center` as an optional parameter to the `drawImage` command.  It's kind of just a convenience option, since it doesn't add any real capability that isn't already possible with the `offset` parameter.  But getting a galaxy drawn at the right position with `offset`, especially when letting GalSim automatically size the image for you, is kind of a pain.  An example was in demo9, and it was pretty confusing.
Now a whole bunch of code in demo9.py has gone away, and the draw command changed to
```
final.drawImage(wcs=local_wcs, center=image_pos)
```
This makes me happy.  :)  I didn't propagate this change to anywhere …
> Add center option to drawImage command

- CHANGELOG.rst
- galsim/utilities.py
- tests/test_utilities.py
I just discovered that our horner and horner2d functions had a bug when the inputs are complex.
Basically, it was recasting them to float for no good reason.  I guess maybe thinking to recast int or float32 arrays to float, but I don't think that's actually necessary, so better to not bother about that.  Anyway, fixed here.
> Fix horner and horner2d for complex inputs

- galsim/vonkarman.py
- include/galsim/LRUCache.h
- include/galsim/SBVonKarman.h
- include/galsim/SBVonKarmanImpl.h
- pysrc/SBVonKarman.cpp
- src/SBVonKarman.cpp
- tests/test_vonkarman.py
Adds undocumented `_force_stepk` kwarg to `VonKarman`.  If present, then calculation of real-space profile is delayed until needed by photon shooting, `getHalfLightRadius`, or `xValue`.  
I decided that in the case where the table build is triggered, it was simplest to repeat exactly the same calculation as if `_force_stepk` was not specified.  The only difference is that `_stepk` is not updated from its previously forced value.
Most functionality is therefore the same between the forced and unforced version of `VonKarman`, with the notable exceptions of speed for the create-through-drawFFT cycle, and `getGoodImageSize`.
In the Piff atmospheric PSF fitting context, using `_force_stepk` leads to a 10x speed improvement.
> Add _force_stepk to VonKarman

- galsim/phase_psf.py
- tests/test_optics.py
Addresses #1061 .  Adds and tests a few more variants of OpticalPSF and specifically how it `obj == eval(repr(obj))` round trips.
> Clean up OpticalPSF repr

- galsim/knots.py
- tests/test_knots.py
The optimizations to RandomKnots done in #1051 introduced a bug when a RandomKnots object is multiplied by an SED.  The bug was discovered by @matroxel and @masayamn and reported in issue #1064.
The solution implemented here is to check for this and call back to the GSObject implementation in that case.
> #1064 Fix bug in RandomKnots when multiplying by an SED

- galsim/__init__.py
- galsim/photon_array.py
- tests/test_photon_array.py
Adds Refraction surface operator.  Pretty straightforward.  A couple design choices include:
• Assumes surface normal is along z-axis.  I think this is sufficient for GalSim, we can do something more complicated in ImSim via batoid in the future if desired.
• In case of total internal reflection, NaNs the dxdz and dydz values, and zeros the flux values, but does not otherwise raise any errors or warnings.
> Add Refraction surface op

- galsim/wfirst/wfirst_psfs.py
This is a very short docstring-only PR that originated from a discussion with @matroxel and @rmjarvis about the WFIRST PSFs.  Hopefully this update is more clear.  The PR is to go into master, but I think it could perhaps also be cherry-picked onto releases/2.2?
> clarify provenance of numbers in WFIRST PSF module

- .gitignore
- devel/lsst/focus_depth.py
- galsim/__init__.py
- galsim/photon_array.py
- tests/test_photon_array.py
This was mostly straightforward.  
The tricky bit, that TBH I'm not sure I've fully addressed, was figuring out the units of the photon_array `.x` and `.y` attributes, specifically in the context of surface operation `applyTo` methods.  I think these are pixels, which means that the `depth` keyword here also makes the most sense in units of pixels.  (One could use the localwcs to express the depth in arcsec I suppose, but that feels even more confusing than pixels).  It's also not clear to me what one should do if the pixels aren't actually square, but hopefully that's sufficiently unusual as to not be a problem.
> #1069 FocusDepth surface operator

- .travis.yml
- galsim/fitswcs.py
- galsim/gsobject.py
- galsim/phase_screens.py
- src/PhotonArray.cpp
- tests/test_airy.py
- tests/test_box.py
- tests/test_convolve.py
- tests/test_draw.py
- tests/test_exponential.py
- tests/test_gaussian.py
- tests/test_interpolatedimage.py
- tests/test_kolmogorov.py
- tests/test_moffat.py
- tests/test_photon_array.py
- tests/test_second_kick.py
- tests/test_sersic.py
- tests/test_spergel.py
- tests/test_vonkarman.py
- tests/test_wcs.py
This PR adds a way to draw photons without actually accumulating them onto an image.
It is functionally equivalent to `_, photons = obj.drawPhot(im, ...)` but without requiring the image.
@cwwalter
> Add obj.makePhot method

- CHANGELOG.rst
- SConstruct
- conda_requirements.txt
- galsim/bandpass.py
- galsim/catalog.py
- galsim/cdmodel.py
- galsim/config/extra_truth.py
- galsim/config/gsobject.py
- galsim/config/value.py
- galsim/config/value_eval.py
- galsim/correlatednoise.py
- galsim/download_cosmos.py
- galsim/errors.py
- galsim/fits.py
- galsim/interpolant.py
- galsim/interpolatedimage.py
- galsim/phase_psf.py
- galsim/phase_screens.py
- galsim/sed.py
- galsim/utilities.py
- galsim/wcs.py
- galsim/wfirst/wfirst_psfs.py
- requirements.txt
- setup.py
- tests/test_des.py
This is a bit of a "spring cleaning" PR.
I've come to realize that our python usage has very few bits that require the future module, so I'm inclined to remove it as a dependency.  Here are the places where we are currently using `future` and my proposed (via this PR) changes:
1. `basestring`: I found a cute way to define basestring that works in both 2 and 3: `basestring = ("".__class__, u"".__class__, b"".__class__)`.  This captures `str`, `unicode` and `bytes` properly on both.  I put this in utilities.py and import from there when we want it.
2. `exec_`: Turns out the python 3 version of `exec` works just fine in python 2.7.  I think the `future.exec_` workaround must have been for python 2.6, which we don't support anymore.  So I just switched exec_ -> exec, and it works fine.
3. …
> Remove future as a dependency

- CHANGELOG.rst
- galsim/fitswcs.py
- galsim/gsobject.py
- galsim/image.py
- galsim/wcs.py
- tests/test_deprecated.py
- tests/test_wcs.py
This is a quick hit to address issue #1073.
For non-local WCS types, the name `withOrigin` is deprecated in favor of `shiftOrigin`.  The functionality hasn't changed, but the name withOrigin is only really appropriate for LocalWCS types.  When the WCS already has a non-zero origin, then the action takes in really to shift the origin, not set a new value.
I kept the name withOrigin for local WCS types where I think it is more intuitive and accurately describes the action taken.  Both names are available for LocalWCS types and they are equivalent.
I also updated the docs a bit to hopefully make the action that is happening here somewhat clearer.
> Change withOrigin -> shiftOrigin for non-local WCS types

- .gitignore
- .travis.yml
- SConstruct
- docs/install_pip.rst
- pyproject.toml
- requirements.txt
- setup.py
Since version 2.0 let us do `pip install galsim`, installation problems have been much reduced.  The only thing left that seems to be somewhat unreliable about the installation is Eigen.  Specifically my attempt to make it work automatically via eigency.
This doesn't always work, and lately has been hitting a bug in numpy, which they don't seem to have any plans to fix.  cf. #1076.  (See also #1035, and indeed all of the pip installation issues on the [FAQ](https://github.com/GalSim-developers/GalSim/wiki/Installation-FAQ-(pip,-setup.py)#2-installing-with-pip).)  There have been other bug reports people have sent separately, and I usually recommend `conda install eigen`, which works great, but requires conda, so doesn't work for everyone.
Anyway, this PR tries to fix this by getting rid …
> Rather than eigency, download eigen from internet if it's not already installed.

- CHANGELOG.rst
- galsim/fits.py
- tests/test_image.py
I was having trouble getting fpack to work on a system, and I realized that GalSim already did what I needed using readMulti and writeMulti.
Except that it didn't quite work correctly.  I discovered that writeMulti didn't properly write the header information when there were non-trivial headers on the images, so the round trip lost the header values I needed from the original files.
So this PR fixes that, and also adds a note about how to effect at least a very simple version of fpack and funpack with galsim, and tests these operations that they preserve at least most of the header values.  (Some get changed by astropy's verify operations, so I skip those.)
> Test an equivalent to a simple version of fpack/funpack using galsim.fits functions.

- CHANGELOG.rst
- examples/demo13.py
- galsim/roman/roman_psfs.py
- galsim/table.py
- galsim/wcs.py
- tests/test_roman.py
@troxel pointed out a subtlety with the Roman PSFs that we had been doing wrong in demo13 and which he also did wrong in his WFIRST sims.  Namely, the PSF that is returned by `galsim.roman.getPSF` is oriented with respect to the image coordinates, not world coordinates.  
While it is in arcsec (not pixels, so kind of in world coordinates), the pupil plane rotates with the camera, so observations with different PA values don't have the diffraction spikes rotate correctly as the telescope rotates.  This led to coadd images in Troxel's sims having very pronounced spikes, whereas we actually expect them to be washed out by the varying PA angles.
This PR fixes that by adding an optional `wcs` parameter to the `getPSF` function.  To get the PSF in world coordinates (as is standard everywhere …
> Update Roman PSF orientation

- CHANGELOG.rst
- devel/time_sersic.py
- docs/bessel.rst
- docs/integ.rst
- galsim/bessel.py
- galsim/integ.py
- galsim/photon_array.py
- include/galsim/SBMoffatImpl.h
- include/galsim/integ/Int.h
- include/galsim/math/Bessel.h
- include/galsim/math/Hankel.h
- pysrc/Bessel.cpp
- pysrc/Integ.cpp
- src/SBKolmogorov.cpp
- src/SBMoffat.cpp
- src/SBSecondKick.cpp
- src/SBSersic.cpp
- src/SBVonKarman.cpp
- src/math/BesselRoots.cpp
- src/math/Hankel.cpp
- src/math/files.txt
- tests/test_bessel.py
- tests/test_chromatic.py
- tests/test_integ.py
- tests/test_kolmogorov.py
- tests/test_vonkarman.py
@damonge recently pointed me to a clever method for computing Hankel transforms:
http://www.kurims.kyoto-u.ac.jp/~prims/pdf/41-4/41-4-40.pdf
The paper is kind of technical math and mostly involves proofs about the method converging and whatnot, but if you want to take a look, the upshot is found in equation 5.2.  The Hankel integral is approximated as a sum of function evaluations that get closer and closer to the zeros of the bessel function.  Since J_nu(x) is part of the integrand, this means that the items being summed get very close to zero very rapidly, so the series can be truncated after not very many terms.
It's worth pointing out that this algorithm is implemented in python in the [hankel](https://github.com/steven-murray/hankel) package, which is also quite nice, although it …
> Use Ogata, 2005 algorithm for computing Hankel transforms.

- CHANGELOG.rst
- galsim/lensing_ps.py
- galsim/table.py
- galsim/utilities.py
- src/Table.cpp
- tests/test_phase_psf.py
- tests/test_table.py
@jmeyers314 Here is what it would look like to switch the convention of LookupTable2D.  I think this is a net positive, since most of the changes to unit tests and such were to get rid of transposes that were used in various places to account for the reverse convention being used here.
However, there are two down-sides of which I'm aware:
1. This is an API change.  I called it out in the CHANGELOG, but this isn't one that would be easy to go through a deprecation stage.  I think it's minor enough that it doesn't require a major version number, but we could go to 3.0 if you think that would be more appropriate.  I'm fine either way.
2. The internal calculations in `T2DGSInterpolant::interp` are now a bit slower.  Reversing the storage order means that the sums now cut across the rows …
> Switch the (x,y) order convention in LookupTable2D

- include/galsim/fmath/fmath.hpp
The fastmath routines require x86 CPUs.  This PR adds in a check and reverts to standard library exponential and logarithms on non-x86 (e.g. Apple Silicon) CPUs.
> Bypass fmath on non-intel CPUs.

- CHANGELOG.rst
- src/SBKolmogorov.cpp
- src/SBSecondKick.cpp
- src/SBVonKarman.cpp
- tests/test_kolmogorov.py
- tests/test_optics.py
- tests/test_phase_psf.py
- tests/test_vonkarman.py
@jchiang87 noticed a bug introduced in commit 56003a938963ba4bef875c2b34fadeb41fb25bf7 (part of PR #1099) where if folding_threshold was too small, R would never be set and stepk was way too large.  
This was a straight bug in that commit.  But in investigating it, I realized that the old implementation of stepk for Kolmogorov was also not very accurate, especially for very low folding_threshold.  The problem is that the accumulation of the integral is just a crude rectangular rule integral, which isn't accurate enough to tell precisely when the integral reaches 0.999999 (for instance).  
So here, I use the high-r asymptotic power law form for the Kolmogorov profile and use that directly to estimate what radius encloses (1-folding_threshold) of the flux, by analytically doing the integral …
> Improve the accuracy of Kolmogorov stepk for very low folding_threshold

- examples/demo9.py
- galsim/config/extra.py
- galsim/config/input.py
- galsim/config/util.py
- tests/test_random.py
This addresses issue #1112.  @erykoff pointed out that some uses of multiprocessing, especially in the config layer, fails when using a 'spawn' context.  Some versions of Python 3.8 (notable MacOS) have made that the default, so they fail.  Linux still seems to use 'fork' as the default, so the CI tests of 3.8 have been passing.
Anyway, it's probably best to be explicit about our use of 'fork' where necessary, so I added context stuff in various places to use 'fork' where it was necessary for the unit tests in python 3.8 on my Mac to pass.
This PR is directed at the releases/2.2 branch.  This is in support of issue #1115 to make a 2.2.5 release that works in Python 3.8.  I'll cherry pick it over to main after merging.
> Use the fork context explicitly in some places where spawn fails

- docs/config_values.rst
- galsim/config/input_nfw.py
- galsim/config/input_powerspectrum.py
- galsim/config/stamp.py
- galsim/config/value_eval.py
- tests/test_config_image.py
- tests/test_config_value.py
@beckermr recently ran into a bit of cruft in the config processing that would be worth cleaning up before the next release.  He discovered that config['world_pos'] is not necessarily the real world_pos.  If the wcs is a CelestialWCS, then world_pos is a tangent plane projection.
There isn't any good reason for this behavior, and it's confusing, so the PR changes it to something more sensible.  Specifically, world_pos is whatever the current world_pos is as we normally talk about it.  If world_pos is a CelestialWCS, then we also have a uv_pos, which is the tangent plane project, which enables the use cases that the old behavior used to enable (namely having a flat "world" position for NFW halos or shear power spectra fields).
> Fix config world pos to be the real world_pos, not tangent plane projection

- CHANGELOG.rst
- galsim/fits.py
- galsim/fitswcs.py
- galsim/wcs.py
- tests/test_image.py
- tests/test_wcs.py
If a FITS file doesn't have any WCS information in it, we default to a PixelScale.  This is currently done silently.
This PR adds a warning that is emitted by default when reading this via `FitsWCS(file)`, but is suppressed by default when reading via `galsim.fits.read(file)`.
If you want to get the warning, you can now do `galsim.fits.read(file, suppress_warning=False)`, and it will emit the warning.  (So you can potentially catch it and do something particular if this happened.)
> Add option to get warning about WCS defaulting to PixelScale (#1120)

- CHANGELOG.rst
- galsim/_version.py
- setup.py
@erykoff has been trying out the new shared library build for use with the LSST DM stack, and found some problems.  Specifically, it had required adding `-lfftw3 -fopenmp` when using the library, which is not ideal.
This PR is to fix the linking steps to work better to not need to explicitly add these link flags whenever using the libgalsim.so library.
Will release 2.3.1 with this fix when Eli gives me the go ahead.
> Fix shared clib

- galsim/chromatic.py
- galsim/sed.py
- tests/test_sed.py
@matroxel ran into a rare bug in the Roman simulations where some wavelengths would be barely outside of the allowed range for the PSF (which is based on the bandpass limits):
```
galsim.errors.GalSimRangeError: Shooting photons outside the interpolated wave_list Value [1192.14102378 
972.39138558 1058.912179  ... 1170.73736364 951.20426042 1180.4948833 ] not in range [885.0, 1245.0]
```
First, that error message isn't particularly useful, since most of the wavelengths are fine.  So I changed the messaging to only list the bad wavelengths.  That produced error messages like the following (for a different band than above):
```
galsim.errors.GalSimRangeError: Shooting photons outside the interpolated wave_list Value 
[1604.9999999999998] not in range [1605.0, 2090.0]
```
Clearly this is …
> Fix rare possibility of SED.sampleWavelength generating wavelengths outside of bandpass limits.

- .github/workflows/ci.yml
- CHANGELOG.rst
- galsim/image.py
- include/galsim/Image.h
- include/galsim/ImageArith.h
- include/galsim/SBShapelet.h
- include/galsim/Std.h
- pysrc/Image.cpp
- setup.py
- src/Image.cpp
- src/Laguerre.cpp
- src/hsm/PSFCorr.cpp
- src/mmgr.cpp
- tests/TestImage.cpp
- tests/test_image.py
This is a quick PR to add some convenience functions to the Image class.
I recently wanted to make a transpose of an image, and we don't have anything out of the box that does this.  It's not too hard to do by hand, but it still seems like it would be nice to have this natively.  While I was at it, I added a few other similar methods that could be potentially useful:
im.transpose - swaps x,y coordinates
im.flip_ud - flips y values ("up and down")
im.flip_lr - flips x values ("left and right")
im.rot_cw - rotates 90 degrees clockwise
im.rot_ccw - rotates 90 degrees counter-clockwise
im.rot_180 - rotates 180 degrees
In all cases, the returned image has either the same bounds or the transposed bounds.  That feels more natural I think than the other choices.  If the user wants something …
> Add methods to flip and rotate an Image

- .github/workflows/ci.yml
- include/galsim/Bounds.h
- include/galsim/Polygon.h
- include/galsim/Silicon.h
- setup.py
- src/Polygon.cpp
- src/Silicon.cpp
- tests/test_sensor.py
This PR changes the internal storage of the pixel boundaries from double to single precision.  I made sure everything still uses double precision for all calculations, so there isn't too much loss of precision in the various places.  
This is most important when the sides may add 1 to their positions depending on which side of the square they are on.  If these are done in single precision, there is more loss of precision.  Probably still acceptable, TBH, but it seems prudent to do as much as possible in double precision nonetheless.
Anyway, only one test ended up needing to be relaxed in its precision, and I dug into it and convinced myself that it is unavoidable.  Basically, it's when we first apply the tree rings to all the boundaries, then go back and calculate areas.  This necessarily …
> Use single-precision for Silicon internal storage

- examples/demo11.py
- galsim/sensor.py
- include/galsim/Silicon.h
- pysrc/Silicon.cpp
- src/Silicon.cpp
- tests/run_examples.py
- tests/test_sensor.py
This PR moves all the logic of when to do the pixel updates from the C++ accumulate function to the python layer function.
This should make it much simpler for us to adjust how this is done when we are accumulating over the whole image at once rather than just doing one object at a time.  But so far I haven't changed any logic -- just made the appropriate hooks available in python.
> Move Silicon recalculation logic to python layer

- galsim/config/process.py
- tests/.coveragerc
- tests/.gitignore
- tests/config_input/multirng.yaml
- tests/template_register.py
- tests/test_config_image.py
This PR adds the option to register template names, so people can use that rather than a file name.
The target use case is imSim, so it can register names like 'dc2_image' or 'flat_field', etc., which could point to a config file in the imSim repo.  This file location is likely to be slightly obscure, so having a comprehensible alias would be both easier for the user and more portable across platforms.
> Add feature to allow registration of templates

- galsim/chromatic.py
- galsim/phase_psf.py
- galsim/photon_array.py
- tests/test_phase_psf.py
- tests/test_photon_array.py
Abuses the `PhotonArray.dxdz` and `.dydz` attributes to hold onto pupil samples generated by `PhaseScreenPsf._shoot`.
I realized along the way that we may wish/need to propagate these values forwards through photon array convolutions, so the rule is if exactly 1 convolutant has `.dxdz` or `.dydz`, then the result will just get the same values.  If more than one convolutant has these attributes, then an exception is raised.
I went ahead and also implemented similar logic for wavelengths, except in this case, GalSim already had a case where two photon arrays with populated wavelength arrays would be convolved; in `ChromaticObject.applyTo`.  Here, it's actually innocuous, since the two photon arrays will have the _same_ wavelength arrays by construction.  So to allow this code to continue as …
> Persist pupil samples uv in photon array

- CHANGELOG.rst
- galsim/gsparams.py
- galsim/image.py
- galsim/interpolant.py
- galsim/interpolatedimage.py
- include/galsim/Image.h
- include/galsim/Interpolant.h
- include/galsim/ProbabilityTree.h
- pysrc/Image.cpp
- setup.py
- src/Image.cpp
- src/Interpolant.cpp
- tests/test_interpolatedimage.py
One of the persistent issues with using PSF models such as those from PSFEx or Piff is that they generally model the "effective PSF", including the pixel convolution, rather than the underlying true PSF.  This means that any objects that use this PSF object have to be rendered with `method='no_pixel'`, rather than `'auto'`, or especially `'phot'`.  Using photon shooting would implicitly convolve a second pixel, so lead to significant biases in the resulting images.
This PR adds the capability of fitting for a "depixelized" image to input into `InterpolatedImage`, which would represent the underlying profile, without the pixel convolution.  The expected user API for this is simply to add the parameter `depixelize=True` to the `InterpolatedImage` constructor.  
Then, to use a Piff model, …
> Add option to have InterpolatedImage de-pixelize the image

- docs/config_image.rst
- galsim/config/noise.py
- tests/test_config_noise.py
This fixes a bug where the CCDNoise class does not return the variance in ADU units, matching the other methods that deal with variance. 
closes #1166
> BUG return variance in ADU units for CCDNoise

- galsim/interpolatedimage.py
@nevencaplar pointed out a change in behavior of the semi-private function `_InterpolatedImage`, which wasn't properly documented.  It now doesn't recenter the input image to have its center at (0,0).  I don't remember exactly the reason for the change in behavior, but the change didn't get properly captured by the doc string.  So this update fixes the documentation to explain how the centering works now.
> Update _InterpolatedImage docs to reflect change in center conventions

- galsim/__init__.py
- galsim/chromatic.py
- galsim/gsobject.py
- galsim/phase_psf.py
- galsim/photon_array.py
- tests/test_chromatic.py
- tests/test_phase_psf.py
- tests/test_photon_array.py
Same idea here as #1176 where we factored out pupil sampling from `PhaseScreenPSF._shoot`.  This time, factor out the temporal sampling.  This isn't immediately useful for anything directly inside GalSim, but would likely be important if we want to rotate the diffraction spikes on an Alt-Az mounted telescope in the future, e.g..
> Add TimeSampler

- CHANGELOG.rst
- galsim/chromatic.py
- galsim/config/extra_psf.py
- galsim/config/gsobject.py
- galsim/config/image.py
- galsim/config/image_scattered.py
- galsim/config/image_tiled.py
- galsim/config/photon_ops.py
- galsim/config/stamp.py
- galsim/gsobject.py
- galsim/image.py
- galsim/photon_array.py
- tests/test_config_image.py
- tests/test_config_output.py
- tests/test_draw.py
- tests/test_image.py
- tests/test_photon_array.py
@jmeyers314 noticed some clear typos in the PhotonDCR `opt_params` class variable, which made it obvious that we don't have any unit tests testing the various ways to make a PhotonDCR object in the config layer.  So this PR adds some.
Along the way, I discovered the following minor bugs and a few features I thought we should have, so I fixed them as well:
* There was no way to specify the dtype of the image made by config processing.  Usually float32 is fine, but we should be able to specify something else if we want.  So now, the image field takes an optional `dtype`, which can be e.g. `np.float64', 'int', 'float', 'numpy.uint32', etc.  Basically all the types that images can be using either np or numpy prefixes where appropriate.
* When testing that feature with int images, I discovered …
> #1148 Fix PhotonDCR config layer bugs, along with a number of other edge cases it turned up.

- docs/misc.rst
- galsim/config/util.py
- galsim/phase_screens.py
- galsim/random.py
- galsim/utilities.py
- galsim/wcs.py
- include/galsim/Random.h
- src/Random.cpp
- tests/test_config_value.py
- tests/test_phase_psf.py
- tests/test_random.py
This is mostly an efficiency PR to speed up random number generation on large arrays.
When working on [this imSim PR](https://github.com/LSSTDESC/imSim/pull/284) involving raining lots of photons through a sensor object, I was finding that with the OpenMP stuff for the sensor, the pure random number generation was taking almost half the total clock time.  The `generate` calls were running on a single thread, and then the `accumulate` calls were being well parallelized.  My laptop can run 10 threads, so it made a big difference.
This PR enables OpenMP parallelization for the various kinds of RNG `generate` functions that we have.  In practice, it's mostly the `generate` call, but I did all of the various flavors.  
Some RNG types (most notably Poisson) don't reliably use 1 rng per …
> Implement OpenMP for random deviate generate functions

- galsim/config/process.py
- galsim/config/util.py
- tests/test_config_image.py
@g-braeunlich found that the current syntax for deleting an item from the config doesn't work to delete things from a list.  This PR remedies this.
The one potentially confusing thing that can result from this is if the user also wants to modify other items in the same list.  Once an item is deleted, these would need to use the new indices, not the original ones.  This seems enough error-prone that I emit a logger warning.
I've targeted this to releases/2.4.  I think this can count as a bug, so could go into a bugfix release.
> Make it possible to delete items from a config list

- galsim/config/input.py
- galsim/config/input_powerspectrum.py
- tests/test_config_image.py
This fixes another bug discovered during imSim development.  @jchiang87 found that sometimes the skycatalog input object wasn't being loaded correctly when there were multiple ccds being rendered in the same config run.  It took me a while to figure out the problem, but it stemmed from how the `current` item was being set (and checked), which was different from how I do that for regular (non-input) values.  It mostly worked, but wasn't quite correct, leading to the bug that Jim found.
Anyway, this mostly just switches over the current checks there to more closely mimic the way I do it elsewhere.  And I added a unit test that fails for the old code, but works now.  
TBH, I feel a little silly about not already having written this test, which would have found the error sooner.  It's sort of …
> Fix bug in how input fields check when they are current

- include/galsim/Image.h
- src/Image.cpp
- tests/test_hsm.py
- tests/test_interpolatedimage.py
The asserts in the hsm code are not correct when either step or stride is negative.  For now, just skip these checks when either step or stride is negative.  But possibly down the line we might want to make this check more rigorous to include the case of negative steps or strides.
> Fix hsm assert when step or stride is < 0

- CHANGELOG.rst
- galsim/photon_array.py
- tests/test_deprecated.py
- tests/test_photon_array.py
Currently, accessing any array in PhotonArray will make sure that it gets allocated if it isn't already and then return the relevant numpy array.  This is intended to make it easy for the user, who can just pretend all the arrays are already allocated and initialized to zeros, but only use up that memory if the user actually indicates that they are using the arrays.
However, Josh pointed out that this can be confusing if you think you've assigned values to something, but didn't and then access the arrays, it will happily give back zero arrays.  This is likely almost always an error.  And for the rare cases where the user might have intended this usage (e.g. doing `rng.generate(photon_array.dxdz)` to populate it), it's easy to just explicitly call `allocateWhatever()` first to make sure …
> Deprecate getter allocation in PhotonArray

- CHANGELOG.rst
- galsim/config/image_scattered.py
- tests/test_config_image.py
Josh discovered that the Scattered type doesn't respect `world_pos` if it's in the stamp field, as it should.  Instead it adds its own `image_pos` specification in the image field, which ends up taking precedence.
It turns out that an `image_pos` in the stamp field did work, kind of by accident, just because when we make the position, it checks stamp first, finds it, and uses it, and just ignores the default one that was made in the image field.  But now the Scattered function explicitly checks the stamp field and only makes the default if there are no other positions anywhere.
> Fix Scattered positions if world_pos is in the stamp field

- .github/workflows/ci.yml
- CHANGELOG.rst
- galsim/_version.py
- galsim/gsobject.py
- tests/test_draw.py
- tests/test_photon_array.py
@g-braeunlich discovered that using photon_ops with method='fft' doesn't quite work as intended.
First, if you don't explicitly give a sensor object, then it bails out telling you that this isn't allowed.
Second, there is no way to limit the number of photons used as we do when photon shooting very bright objects, so the memory explodes if you try to do this for very bright objects (as we want to do in imSim).
So this fixes some of the sanity checks to work correctly when the user is applying photon ops on an fft image.  And it implements the maxN parameter for this use case, following the same pattern as we do in drawPhot.
> Fix some problems when using photon_ops with fft drawing.

- galsim/config/input.py
- galsim/config/input_cosmos.py
- galsim/config/input_real.py
- tests/test_galaxy_sample.py
This PR fixes a long term annoyance about input objects in the config.  We use Proxies to avoid having input objects get cloned into every process, since they are often relatively large.  This works fairly well, but there is a catch -- the standard multiprocessing AutoProxy class doesn't expose attributes and properties of the wrapped object.  Just methods.  So you need to write getters for any attribute you want to access.  This has recently become onerous in ImSim.
Fortunately, @jmeyers314 discovered [this SO answer](https://stackoverflow.com/a/63741184/1332281), which shows how to circumvent this behavior.  I actually used a [slight modification](https://stackoverflow.com/a/65466807/1332281), which doesn't use exec, and then had to fix a …
> Let Input Proxy objects access attributes, not just methods.

- CHANGELOG.rst
- galsim/config/image.py
- galsim/config/image_scattered.py
- galsim/config/image_tiled.py
- galsim/config/input.py
- galsim/config/output.py
- galsim/config/photon_ops.py
- tests/test_config_input.py
The calculation of the number of objects on each image in imsim can take quite a while when doing a lot of CCDs, since it needs to load the WCS and compute the overlap of the CCD with heal-pixels, etc.  This is currently being done in the serial part of the processing, rather than the parallel part, since GalSim needs to know the object numbers to assign to each image before starting the parallelization.  
However, we realized that this doesn't really need to be precise.  An approximage estimate of the number of objects is fine.  Or really an upper bound.  And in fact, if it misses and accidentally under-estimates, it's not the end of the world for most use cases.  It would just end up in some objects having the same random number sequence for whatever they use that for.
So this PR adds …
> Allow input objects to return an approximate number of objects.

- galsim/download_cosmos.py
- galsim/main.py
- tests/test_main.py
This pull request adds the `--log_format` option to the GalSim executable. The default behavior is `"%(message)s"` (i.e., consistent with the past behavior of the GalSim logger).
Example usage would be
```
$ galsim --log_format="%(asctime)s - %(name)s - %(levelname)s - %(message)s" demo1.yaml 
2022-12-13 14:12:47,824 - galsim - WARNING - Reading config file demo1.yaml
2022-12-13 14:12:47,834 - galsim - WARNING - Start file 0 = output_yaml/demo1.fits
2022-12-13 14:12:47,858 - galsim - WARNING - File 0 = output_yaml/demo1.fits: time = 0.024030 sec
2022-12-13 14:12:47,858 - galsim - WARNING - Done building files
```
> Add --log_format to GalSim executable

- src/SBProfile.cpp
- tests/.coveragerc
- tests/test_celestial.py
- tests/test_draw.py
@jecampagne noticed a bug in the C++-layer `SBProfile.draw` function that gets the flux wrong when using `drawReal` on an non-unit-pixel-scale image with an object with a non-diagonal Jacobian.  cf. discussion on #1197
Fortunately, this is a pretty obscure edge case, so I suspect it's unlikely this has ever caused a problem in practice.  But it's definitely better to have the code correct, of course.  :)
Fixes #1197
> Fix the flux scaling of drawReal for objects with non-diagonal jacobian

- README.rst
- docs/real_gal.rst
- galsim/__init__.py
Made some minor README/documentation updates compared to releases/2.4 (just fixing broken URLs since great3challenge.info is gone).
> update GREAT3 links

- CHANGELOG.rst
- galsim/config/util.py
- tests/test_image.py
We have a class in GalSim config called LoggerWrapper, which is intended to avoid communicating with the main logger via the proxy when we aren't actually going to output anything.  E.g. logger.debug statements when the logging level is only INFO or WARNING.  This is mostly a big improvement.
However, @beckermr and @jchiang87 have each recently found huge inefficiencies when running on Perlmutter with ~128 processes.  I tracked it down to when we make a new LoggerWrapper instance and call `logger.getEffectiveLevel()`.  This had always been going back to the original proxy logger instance even when we already have a wrapped one.  And for lots of processes, this can end up clogging the inter-process communication completely unnecessarily. 
This PR makes the fairly trivial change that when …
> Fix LoggerWrapper inefficiency

- include/galsim/SBMoffat.h
- include/galsim/SBMoffatImpl.h
- src/SBMoffat.cpp
- tests/test_chromatic.py
- tests/test_config_output.py
- tests/test_convolve.py
- tests/test_draw.py
- tests/test_interpolatedimage.py
- tests/test_moffat.py
@jecampagne pointed out an error in our maxk calculation for Moffat.  See details in #1208.  The upshot is that our Moffat FFT renderings were a bit more accurate and a bit slower than they needed to be for the nominal maxk_threshold.  This PR fixes the calculation to be only as accurate as requested.
> Fix error in Moffat maxk calculation

- galsim/gsobject.py
- galsim/photon_array.py
- src/PhotonArray.cpp
- tests/test_photon_array.py
@g-braeunlich ran into a bug in the PhotonArray `makeFromImage` function where it would sometimes seg fault.  It turned out that the calculation for how many photons would be needed was wrong when there were negative-flux pixels, so it wasn't allocating enough space and the arrays were being overrun.  This PR fixes that bug.  
It also happened to be the case that that function shouldn't even have been run for what Geri was doing.  But he had the photon_ops set to [], rather than None.  Those should logically mean the same thing, but GalSim assumed that since photon_ops wasn't None, it needed photons.  Now photon_ops = () or [] means the same thing as None in the code.
> Fix possible crash in PhotonArray.makeFromImage if image has negative pixels.

- CHANGELOG.rst
- galsim/hsm.py
- tests/test_hsm.py
This PR involves code that I've been copying around to various places (e.g. it is in the piff.Star.hsm method) knowing each time that I should really put it into GalSim directly.  But it was always more expedient to just copy it.  So today, as I was about to copy it yet again, I decided to do it right and add it here.
The HSM moments are natively measured in pixel coordinates.  Indeed the back end code doesn't have any knowledge of the WCS.  However, it's fairly straightforward to convert these (x,y) moments in to (u,v) moments using the jacobian of the WCS.  This PR adds two ways the user can do this:
`ShapeData.applyWCS(wcs)` converts a ShapeData instance into one where the size and shape values are based on the u,v moments rather than x,y.
`image.FindAdaptiveMom(use_sky_coords=True)` …
> Add options to convert HSM moments to sky coordinates

- CHANGELOG.rst
- galsim/__init__.py
- galsim/config/util.py
- galsim/config/value_eval.py
- tests/test_config_value.py
@jmeyers314  discovered a bug in the config parsing that prevented Eval types from being used to generate a list object, when parsed in the normal way.  The oversight was that list (and dict and LookupTable) were not registered as valid types associated with the Eval type.  
The workaround is to use None for the value_type rather than list, but this is inelegant and less type-safe.
> Add list (and dict, LookupTable) as a registered type for Eval

- galsim/config/value.py
- tests/test_config_value.py
I was trying to figure out how to simulate all Rubin sensors in ImSim except the guiders and came up with this snippet:
```yaml
det_num:
type: List
items: $[i for i in range(205) if i not in [189, 190, 193, 194, 197, 198, 201, 202]]  # no guiders
```
The `Eval` within the `List` currently produces `galsim.errors.GalSimConfigError: items entry for type=List is not list-like.`, but is fixed on this PR.
> Enable Eval within List in config

- src/Silicon.cpp
- tests/test_sensor.py
Bekah Polen ran into an edge case where some photons had bad wavelengths being accumulated via the Silicon sensor.  They also had flux=0, so the other details didn't matter, but it was raising an exception that the wavelengths weren't valid for the absorption depth table.
This PR fixes this by taking the absorption depth to be the value for the minimum or maximum valid wavelength whenever the wavelength is too blue or too red, respectively.
We could probably add an optimization to check for flux=0 sooner as an optimization, but I didn't do that here.
> Don't abort if wavelengths are outside valid range for absorption

- include/galsim/Std.h
- setup.py
- src/Silicon.cpp
This PR adds support for building with the NVIDIA compiler, nvc++. This compiler doesn't support one of the warnings commonly enabled in the other compilers so we have to remove it. It also formats its version information a little differently from gcc and clang.
This also adds a missing macro definition for building for GPU with gcc.
> Add support for building GPU-enabled GalSim using NVIDIA compiler

- CHANGELOG.rst
- galsim/utilities.py
- tests/test_sensor.py
Some OMP implemenations have a bug where if omp_get_max_threads() is called (which is what this function does), it sets something called thread affinity.
The upshot of that is that multiprocessing (i.e. not even just omp threading) is confined to a single hardware thread.  Yeah, it's idiotic, but that seems to be the case. The only solution found by @erykoff, who looked into it pretty hard, is to set the env variable OMP_PROC_BIND to "false".  This seems to stop the bad behavior. 
So this PR adds that to the two functions that could potentially call omp_get_max_threads in the C++ layer.
> Set OMP_PROC_BIND=false before calling omp_get_max_threads

- CHANGELOG.rst
- galsim/chromatic.py
- tests/test_chromatic.py
- tests/test_photon_array.py
Josh pointed out in #1229 that chromatic objects with wavelength-dependent transformations don't work with photon shooting.  This fixes that.
I also fixed two other issues in this part of the code:
* GalSim automatically adds a WavelengthSampler to the photon_ops for photon shooting chromatic objects.  But if the user already did that, then it (1) redundantly samples the wavelengths twice, which is inefficient and (2) warns the user that this is likely an error.  Well, IMO, the error is in the GalSim code, not the user code.  So now it skips adding a redundant WavelengthSampler and consequently doesn't emit the warning.
* I realized when writing the test that the handling of the poisson_flux option in ChromaticConvolution was incorrect.  It neglected to apply the g factor returned by …
> #1229 Fix a few errors in photon shooting chromatic transformations.

- CHANGELOG.rst
- galsim/config/__init__.py
- galsim/config/image.py
- galsim/config/image_scattered.py
- galsim/config/image_tiled.py
- galsim/config/input_image.py
- galsim/config/stamp.py
- tests/config_input/sn.yaml
- tests/test_config_image.py
This PR adds the ability for the config processing to read in an initial image from a file and draw additional things onto that.  The implementation is pretty simple:
```
input:
initial_image:
file_name: inital_image_file.fits
```
My test for this is to simulate a supernova time series.  It draws a single reference image, and then draws a point source with variable flux 12 times.  The SN appears between the 3rd and 4th image.  And then it decays exponentially.
> Add initial_image input type

- CHANGELOG.rst
- devel/time_combine_waves.py
- docs/misc.rst
- galsim/utilities.py
- pysrc/PyBind11Helper.h
- pysrc/Utilities.cpp
- pysrc/module.cpp
- tests/test_utilities.py
@jchiang87 found that a significant amount of time in some recent imSim runs was spend doing the `combine_wave_list` function when adding the bulge+disk+knots galaxy components.  This is partly because the SEDs probably have more wavelengths than we really need.  But regardless, this function was not the most efficient bit of code.  This PR significantly improves the algorithm.  In the typical case, it's more than 3x faster.  And when all the inputs are the same (which was the case for imSim in Jim's test) it's almost 5x faster.
The new underlying functionality is a new utility function `merge_sorted`, which merges two or more numpy arrays when the inputs are all already sorted.  This is a pretty simple function (familiar to those who know merge sort), but there is apparently no native …
> Speed up combine_wave_lists using new merge_sorted function

- CHANGELOG.rst
- src/SBTransform.cpp
- tests/test_gaussian.py
@EiffL reported a very slight difference in the rendered images of a shifted profile using FFT rendering vs real space for single-precision images.  It's about 10x higher than the single precision epsilon on my laptop and 100x higher on Google collab, so I went ahead and switched the code to use double precision for the complex phases to avoid the accumulation of rounding errors, which fixed the problem.
Original:
Fixed:
> #1231 Fix slight inaccuracy in single precision fft phase shifts

- CHANGELOG.rst
- galsim/config/input.py
- tests/test_config_input.py
imSim has input types that depend on other input types.  Most notably, many things implicitly depend on opsim_data, which is basically a dict with a bunch of values that things need.  If the inputs are listed in order with dependencies first, everything is fine.  But when using recursive templates, this can be difficult to get right.  Currently, that causes the input items that are dependent on later ones not to load properly.  The most critical of these is atm_psf, which needs to be loaded at the start to only build one set of atmospheric screens for all the CCDs to use.  cf. https://github.com/LSSTDESC/imSim/pull/408
In this PR, when loading an input object, if it raises an exception that indicates it needs a different input type, it tries to load that one first before continuing on.
> Make inputs work if dependent on later input items

- CHANGELOG.rst
- galsim/photon_array.py
- tests/test_phase_psf.py
- tests/test_photon_array.py
When convolving two PhotonArrays, we had a feature where GalSim would check if both of them had various ancillary arrays set (and not identical), and if they were both set, it would raise an exception.  The thought was that this probably indicated an error.  But in practice it meant that when two PhaseScreenPSFs were convolved, they couldn't be drawn with photon shooting, since each of them would have set the pupil coordinates and the time independently.
If you want to be really careful about these ancillary arrays, then you can put the PSFs in photon_ops, in which case they will be processed sequentially and PhaseScreenPSF won't overwrite e.g. pupil coordinates that are already there.  But if you don't much care about these ancillary arrays, it should be allowed to just convolve two PSF …
> Don't error if two photon_arrays being convolved both have allocated ancillary arrays.

- include/galsim/Image.h
- src/Image.cpp
- src/Silicon.cpp
The SiliconSensor class uses a rather large amount of memory when the postage stamp is large.  Proportional to the number of pixels, as you might imagine.  However, once it's done with the large image and goes on to smaller postage stamps, it doesn't release that memory.  This PR lets those vectors release the allocated memory whenever the target image size decreases.  It also does the same with the `_delta` image -- releasing the memory when it gets smaller.
> Let vectors in SiliconSensor release their previous allocated memory when getting a smaller target image.

- CHANGELOG.rst
- devel/time_faint_bd_gals.py
- galsim/chromatic.py
- galsim/config/image.py
- galsim/config/output.py
- galsim/config/stamp.py
- galsim/gsobject.py
- galsim/main.py
- galsim/sed.py
- galsim/table.py
- galsim/transform.py
- tests/test_chromatic.py
- tests/test_deprecated.py
- tests/test_main.py
- tests/test_phase_psf.py
- tests/test_sed.py
I was looking through the profile Jim made recently of an imSim run, which inspired the `combine_wave_list` speed up in #1243.  This PR continues in that vein with various optimizations, mostly related to the SEDs.
* First I realized that for faint objects (which there are many in typical imSim runs!), a lot of those SED calculations end up completely wasted, since their SEDs get replaced with a trivial SED later anyway.  I fixed this by making the SED a property rather than an attribute.  That way if it ends up getting replaced, we never need to do those SED calculations at all.  Of course, in regular usage, it's not much of an optimization, since the same calculation gets done at some point, just not in the constructor, but for faint things in imSim, it definitely makes a big …
> Delay calculation of SED until it is actually needed.

- galsim/sed.py
- tests/test_sed.py
This first commit introduces a new test in `test_sed.py` that fails with the current implementation of `SED._mul_scalar` to address #1254.
> Add test to check fluxes calculated for different flux types and propose fix

- CHANGELOG.rst
- galsim/bandpass.py
- galsim/chromatic.py
- galsim/random.py
- galsim/real.py
- galsim/sed.py
- galsim/table.py
- galsim/utilities.py
- tests/test_bandpass.py
- tests/test_chromatic.py
- tests/test_random.py
- tests/test_sed.py
- tests/test_table.py
This PR addresses a number of things that have turned up in various imsim/roman_sim runs related to the SED classes.  The initial impetus for this work was to let the SEDs we get from skyCatalogs to be picklable, so image.nproc would work correctly, and other use cases as well would not be quite so finicky about pickling.
* The main solution for this problem was to have mul_sed try to return a tabulated sed if possible.  I.e. when either (or both) of them uses a lookup table.
* Another thing that helps for some cases is to not try to pickle the derived SEDs in chromatic objects that have the SED as a lazy_property.  It's not very inefficient to remove them from the dictionary before pickling and remake them if needed.  (Indeed it might be usually more efficient, since there is less …
> Improve behavior of SED class, especially with respect to pickling and spline interpolation.

- galsim/phase_screens.py
- src/Silicon.cpp
- tests/test_sensor.py
In ImSim, we sometimes make a stamp image that is large enough to extend past the allowed range of the treering function.  The treatment outside that range is irrelevant, since we just ignore the part that is outside the bounds of the main image, but the current code was raising an exception.
This PR changes it to just ignore tree rings on any pixels that are outside the range of the treering function.
> Don't err if SiliconSensor accumulates on image outside range of treering function

- CHANGELOG.rst
- galsim/roman/__init__.py
- galsim/roman/roman_wcs.py
For the upcoming Rubin-Roman sims, the time delay group (the TDS PIT) wants to be able to pretend that the ELAIS field is in the Roman continuous viewing zone so the transient light curves don't end up getting split up into discrete seasons.  
I think the least-intrusive way to allow this, without overly encouraging people to just ignore the sun position in Roman observations, is to make the maximum angle between the solar panels and the sun be a galsim.roman module variable, rather than hard-coded.  This is good programming practice anyway (it's currently written as just 36, rather than even named in the function).  And it would allow the roman_imsim package to add an option to edit it to something larger, which would let GalSim still calculate reasonable roll angles and just pretend …
> Add max_sun_angle to the roman module global variables

- INSTALL.rst
- README.rst
- galsim/hsm.py
- galsim/image.py
- test_requirements.txt
- tests/test_hsm.py
This PR addresses a lot of the concerns raised in #1264. I also separated conversion code from code that checks things as much as possible. I can add some additional unit tests if this all looks sensible.
> Optimize bits of HSM code

- galsim/config/process.py
- galsim/config/value_eval.py
- test_requirements.txt
- tests/test_config_image.py
I was trying to craft a graceful solution to ImSim Issue [#452](https://github.com/LSSTDESC/imSim/issues/452), and I think I did, but I ran into a bug in GalSim, which this PR fixes.
Basically, if there is a template embedded in one of the fields of the config dict, and that template uses an eval, then Python doesn't like it, since you end up changing the size of the overall config dict due to the eval_gdict item.  Using `list(config.items())` fixes this issue.
> Fix bug in using eval with templates not at top level

- CHANGELOG.rst
- galsim/wcs.py
- tests/test_wcs.py
@esheldon ran into a bug in the computation of the local Jacobian near ra=0 when using a CelestialWCS.  It's the normal thing about 0 and 2pi not being close to each other, so the finite difference estimate of the jacobian ends up badly wrong.
This bug doesn't affect GSFitsWCS, which has its own implementation of this function.  So that's probably why it hasn't surfaced earlier, but Erin's use case involve a wrapper of the LSST DM wcs class, where this finite difference estimate is used.  The fix is (as usual) to wrap the values to be near one particular value, so the finite differences do what they are intended to do.
> Fix CelestialWCS._local computation of local jacobian when position is near ra=0

- .github/workflows/ci.yml
The new MacOS runners on GitHub actions seem to have recently turned on "System Integrity Protection".  This means the way we had been setting the FFTW include and link directories didn't work right anymore.  We now need to explicitly set FFTW_DIR when doing pip install.
> Fix fftw on new Mac GHA machines

- .github/workflows/ci.yml
- galsim/config/extra_psf.py
- galsim/config/stamp.py
- galsim/deprecated/integ.py
- galsim/image.py
- galsim/lensing_ps.py
- galsim/phase_screens.py
- galsim/table.py
- galsim/utilities.py
- tests/test_config_noise.py
- tests/test_detectors.py
- tests/test_image.py
- tests/test_sed.py
- tests/test_table.py
Numpy made a few changes to their API with version 2.0.  This PR addresses the places where they impact GalSim code.
1. np.array(a, copy=False) is now an error if a copy is required for the dtype.  Using `copy=None` now does the equivalent to what `copy=False` used to do.  But in most cases, it's better to just use `np.asarray(a)`, which is equivalent in both versions.
2. There is one case where we have a more complicated decision about whether to copy, so in that case we need to use an explicit version check to get the right kwarg.
3. They changed the implicit dtype conversion for values in e.g. += and similar operations.  For GalSim purposes, this mostly just required changing test expectations.  E.g. using `Image(..., dtype=float)` when we want to test accuracy at double precision.
4. …
> Updates to be compatible with numpy 2.0

- .github/workflows/wheels.yml
In preparation for releasing version 2.5.3, I added arm wheels to our wheels.yaml script.
Also, PyPi now prefers using trusted publishing.  (cf. https://docs.pypi.org/trusted-publishers/adding-a-publisher/) So I switched to that as well.
This is hard to confirm before actually running the script, which will happen when we make the release tag v2.5.3.  But @jmeyers314 if you can look through it once to see if there are any errors that you can notice in advance, that would be appreciated.
> Update wheel.yml to build ARM wheels and switch to trusted PyPi upload rather than using a token.

- .github/workflows/ci.yml
- CHANGELOG.rst
- galsim/config/value.py
- tests/test_config_value.py
- tests/test_zernike.py
@jmeyers314 noticed in #1299 that a string like '123.4, 567.8' doesn't get parsed correctly.  This PR fixes the implementation to work correctly.
> Fix PositionD parsing in config from strings like '123.1, 234.2', which had been doing the wrong thing.

- galsim/utilities.py
- galsim/zernike.py
- tests/test_zernike.py
> More type checking/promotion in polynomials

- galsim/roman/__init__.py
- galsim/roman/roman_bandpass.py
- tests/test_roman.py
> Include prism bandpasses in the roman module

- galsim/phase_screens.py
- src/SBProfile.cpp
> Add an actual global dbgout for compilers that don't fully optimize it away.

- CHANGELOG.rst
- galsim/gsobject.py
- tests/test_draw.py
cf. #1322
@beckermr @zhouconghao
> Fix centering bug reported in #1322

- .github/workflows/ci.yml
- galsim/spergel.py
- tests/test_airy.py
- tests/test_box.py
- tests/test_exponential.py
- tests/test_gaussian.py
- tests/test_inclined.py
- tests/test_kolmogorov.py
- tests/test_moffat.py
- tests/test_second_kick.py
- tests/test_sersic.py
- tests/test_shapelet.py
- tests/test_spergel.py
- tests/test_vonkarman.py
Fix a bug in the Spergel stepk calculation noticed by @beckermr.  See #1324 for details.
> Fix #1324 and add more regression tests of maxk, stepk, etc.

- galsim/dcr.py
- tests/test_photon_array.py
@vfbraga ran into a bug in the dcr angle parsing where both zenith_angle and obj_coord are set.  This can happen if zenith_angle is given explicitly, and there is a sky_pos being set in the config (which is relatively common).
The fix here is just to allow that combination.  So if zenith_angle is given, the dcr parsing function will pop off obj_coord from the rest of the kwargs that get returned.
> Make PhotonDCR work correctly with both sky_pos and zenith_angle
