CHANGELOG.md
galsim/config/image.py
galsim/config/noise.py
galsim/config/stamp.py
tests/test_config_image.py

This is a one-line fix for the bug noted in #732.  (I also mentioned it in CHANGELOG because in v1.3 it looks like the same error would have occurred.)  
Should I add any unit tests, or is this all good?

#732- quick correlated noise fix

---

galsim/scene.py
tests/test_scene.py

This is very short PR to fix a few bugs that occurs when one tries to get the parametric fits for galaxies from the recently updated COSMOS Catalog.
P.S.: Sorry, I am sleepy and have pushed the fix in existing branches :-/. It shouldn't bother with anything but let me know if it should be reverted.

Minor bug fixes in getting parametric galaxies from COSMOSCatalog

---

galsim/config/output.py

when many parallel jobs are all trying to run `os.makedirs` on the same directory a race condition can occur; the directory is created between the `os.path.exists` check and when `makedirs` is called.  In that case an `OSError` is raised with error code 17 (File Exists).  This pull request adds a helper function to deal with this at the most basic level.
I'm just checking for the OSError and the File Exists error code.  I also make sure that, if the path does exist, it is in fact a directory.
One could get much fancier than this.

Add a makedirs helper function to deal with race conditions

---

examples/demo13.py

This is the PR to fix the an earlier PR (#766) where I broke demo13.py . The quantization of the `sky_image` should happen first and then needs to be added to the `tot_sky_image`.

Fixing the broken demo13

---

CHANGELOG.md
examples/demo4.py
examples/demo4.yaml
galsim/__init__.py
galsim/compound.py
tests/test_randwalk.py

This class generates a set of point sources.  The location of these
is based on a random walk with specified number of steps.
the user can choose the number of point sources, number of steps,
the expected half-light radius of the distribution, and the total
flux in the points.
The points are represented as small galsim.Gaussian objects

add a new profile RandomWalk

---

INSTALL.md
SConstruct

This PR just has edits to INSTALL.md to clarify versions of dependencies and a minimal set of dependencies.

#841 - INSTALL.md updates only

---

SConstruct
src/SConscript
tests/SConscript

- Print function
- has_key -> in

Add Python3 support to SCons files

---

CHANGELOG.md
galsim/sed.py
galsim/utilities.py
tests/test_deprecated.py
tests/test_sed.py

Adds some sanity checks and unit tests for valid redshift inputs to `SED.atRedshift`.

#905 Check for valid redshifts

---

INSTALL.md
README.md

This PR adds conda install instructions

ENH add conda install instructions up front

---

devel/external/time_photon_shooting/time_exponential.py
devel/lsst/time_phase_phot.py
examples/fft_vs_geom_movie.py
galsim/gsparams.py
include/galsim/GSParams.h
include/galsim/OneDimensionalDeviate.h
include/galsim/ProbabilityTree.h
pysrc/SBProfile.cpp
setup.py
src/GSParams.cpp
src/OneDimensionalDeviate.cpp
src/SBExponential.cpp
src/SBInterpolatedImage.cpp
tests/run_examples.py
tests/test_deprecated.py
tests/test_optics.py

I've been looking into ways to speed up the atmospheric photon shooting being used for LSST DC2, and it turns out that one of the tall poles for the brighter objects is the OneDimensionalDevaite::shoot function.  In particular when used by the Airy profile (which is used as part of the second kick).
OneDimensionalDeviate had been treating the profile as piecewise constant intervals, but then (usually) using variable flux to reweight the photons in each interval to get the right net profile.
cf. This comment:
```
If `_useRejectionMethod=false`, then no rejection is done.  The photon is kept, but is given
a flux value equal to the FluxDensity at x relative to the mean over the interval.  This is
faster but makes the statistics of the photons harder to interpret.
```
For many profiles, …

Change OneDimensionalDeviate to use linear approximation rather than constant

---

.travis.yml
devel/time_silicon_accumulate.py
include/galsim/Silicon.h
setup.py
src/Polygon.cpp
src/Silicon.cpp
tests/test_sensor.py

This is my first attempt at adding OpenMP to the photon loop and pixel distortions loop in Silicon::accumulate, as discussed in #1008 . I suspect this code is not yet ready to be merged but it would be good to get feedback on what changes it would need.

Parallelize Silicon::accumulate using OpenMP

---

galsim/phase_screens.py
galsim/utilities.py
tests/test_phase_psf.py

See https://github.com/LSSTDESC/imSim/issues/234

AtmosphericScreen pickling

---

galsim/position.py
tests/test_shear_position.py

This PR adds a shear method to the Position objects so that they can be sheared.

ENH shear the position

---

.github/workflows/ci.yml
examples/demo9.py
galsim/config/extra.py
galsim/config/input.py
galsim/config/util.py
tests/test_random.py

Duplicate of #1116 but targeted to main (and rebased onto main).  I realized that the CI won't run on #1116, since that branch is set up for Travis, which we've turned off now.  So If this one passes the GH Actions CI, then we can merge both.  Anyone who wants to review can do so on either one, since they are equivalent.

Use the fork context explicitly in some places where spawn fails

---

galsim/position.py
tests/test_shear_position.py

This PR backports position shearing to the 2.2 series. We are doing this to work around DM needing another month to update to 2.3.

ENH backport position shearing to 2.2 series

---

galsim/real.py
galsim/scene.py

This is a very short documentation-only PR to add some clarity on what is needed to draw `RealGalaxy` objects (based on a question I received from a user).
Currently it's set up as a PR to the main branch, but we could consider applying it to a release branch.

RealGalaxy documentation updates

---

CHANGELOG.rst
galsim/chromatic.py
tests/test_chromatic.py

See #1156 for description of the problem.
This PR fixes it and adds tests to confirm.

#1156 Fix error in ChromaticSum photon shooting when n_photons is given explicitly

---

CHANGELOG.rst
galsim/bounds.py
tests/test_utilities.py

This is a short PR introducing the feature to expand a bounding box by different factors in different directions. Addresses #1153 .

Expand bounds directionally

---

galsim/config/input.py
tests/config_input_test_modules.py
tests/test_config_input.py

This PR adds the `initialize` method for inputs. 
todo:
closes #1162

ENH add initialize method for input loader

---

galsim/chromatic.py
tests/test_chromatic.py

Fix ZerDivisionError possibility in ChromaticSum photon shooting.

---

galsim/__init__.py
galsim/chromatic.py
galsim/gsobject.py
galsim/phase_psf.py
galsim/photon_array.py
tests/test_chromatic.py
tests/test_optics.py
tests/test_phase_psf.py
tests/test_photon_array.py

Thanks for starting this @rmjarvis .  I changed `PupilSampler` -> `PupilImageSampler` to leave room for `PupilAnnulusSampler` which I added.

Add pupil samplers

---

docs/config_values.rst

@rmjarvis , this held me up a bit this morning.  Not sure if you want to update on v2.4 docs or not.

Fix RADec docs capitalization

---

setup.py

Check for GPU support by actually compiling a GPU program

---

setup.py

This PR adds support for GPU offloading when building with gcc, in addition to the previous clang support. Tested on the Cirrus cluster in Edinburgh with both a version of gcc that supports offloading and one that doesn't.
I also removed the `-stdlib=libc++` stuff from the GPU detection function. I realised that was pointless because neither of the GPU compilers have that flag in the first place.

Support GPU offloading when building with gcc

---

CHANGELOG.rst
galsim/config/process.py
tests/config_input/template.yaml
tests/test_config_image.py

@cwwalter pointed out that the template processing doesn't work correctly if the template file itself has a template field.  This PR fixes that.

Recurse ProcessTemplate call in case template file has further templates

---

CHANGELOG.rst
galsim/sed.py
tests/test_sed.py

Change SED to correctly broadcast over waves when the SED is constant.

---

galsim/wcs.py

This addresses https://github.com/GalSim-developers/GalSim/issues/1262

Fix CelestialWCS.radecToxy docstring erratum

---

galsim/config/util.py
tests/test_config_image.py

This method is missing and I happened to need it. Adding it here.

ENH add critical logger method to logging wrapper

---

.github/workflows/ci.yml
galsim/chromatic.py
galsim/photon_array.py
tests/test_chromatic.py
tests/test_config_image.py
tests/test_photon_array.py

Fixes a few issues with Chromatic objects' use of the save_photons=True option.
Specifically, issues #1271 and #1284.

Fix chromatic save photons
